### ISSUE TITLE
Profile picture seems to not be a perfect circle.

### ISSUE THREAD

**Issue by ghost** [Customa/Customa#34]
![image](https://user-images.githubusercontent.com/64449837/92309792-7832dc80-ef76-11ea-84ab-fcceb69f92ea.png)

Profile picture seems to not be in a perfect circle when status quarters is enabled (even in call, when you see everyone's profile picture when you click on the channel, it shows half of the profile picture).

https://github.com/Customa/Customa-Discord/blob/main/Misc/customSettingsModal.m.css
with
https://github.com/Customa/Customa-Discord/blob/main/Sidebar/statusQuarters.m.css

**Comment by ghostlydilemma** [comment]
Ouch, yeah that module is a breaking in a lot more places than i thought. I will eventually have to rewrite this. Thanks for the issue and the heads up! :)

**Comment by Shivam2498** [comment]
@ghostlydilemma  can you assign me this ?

**Comment by ghostlydilemma** [comment]
Due to limited resources, I have to close this for now

**Comment by ghostlydilemma** [comment]
A featurecomplete replacement for this module seems to be https://github.com/DiscordStyles/RadialStatus
