### ISSUE TITLE
Member Wrapper in NSFW channel seems to break

### ISSUE THREAD

**Issue by ghost** [Customa/Customa#37]
When member wrapper is enabled with Customa base theme, it will break the search function to be off-set to the left and affect the member list to move further to the left with the animate function.

[Example 1](https://gfycat.com/FavoriteElaborateAntlion.gif)
[Example 2](https://gfycat.com/AptHideousHarpyeagle.gif)

**Comment by ghostlydilemma** [comment]
Does that only happen for NSFW channels or was that just to hide your chat content?

**Comment by ghost** [comment]
It only does that if the NSFW chat is censored, otherwise the member wrapper seems to be working as intended if you get past the censor.

**Comment by ghostlydilemma** [comment]
Fixed in 1b1e5b6b54110355fffd453180616691490ed4fa
