### ISSUE TITLE
Using old URLs in some files

### ISSUE THREAD

**Issue by VelvetToroyashi** [Customa/Customa#43]
Just so happened to peak at this: https://github.com/Customa/Customa-Discord/blob/main/WIP/betterJumpLinks.m.css

Both because Discord is Discord, and because of futureproofing, it's probably best this is changed to `discord.com/` instead of `discordapp.com`

**Comment by VelvetToroyashi** [comment]
This file was indeed broken because of the URL change.

**Comment by VelvetToroyashi** [comment]
`discord.com`: https://velvet.is-ne.at/oDficU.png
`discordapp.com`: https://velvet.is-ne.at/59hhg6.png

**Comment by ghostlydilemma** [comment]
WIP Themes are theoretically not maintained yet since i never got quite happy with the results but I'll give it a look!
Thanks for the heads up :3
