### ISSUE TITLE
Theme random stuff in My Account Tab

### ISSUE THREAD

**Issue by Davoleo** [Customa/Customa#53]
**Issue in:** User Settings > My Account

Steps to reproduce: Just open the section written above

Injector used: *Powercord*

Customa Configuration: 
I've literally just changed the background image selector in css to this:
```css
  --BackgroundImg: url('https://i.imgur.com/4HNzDJR.jpg'); /* Color or url('https://i.imgur.com/k6hST83.png') */
```

Screenshot: 
![image](https://user-images.githubusercontent.com/24458276/126383759-44c7a82b-e92a-475e-ad3d-d9a0f0acf52f.png)

**Comment by ghostlydilemma** [comment]
Heya thank you for the issue report. You seem to be using the edited version of Customa from Poilerwags:

- https://github.com/Poilerwags/TransparentDiscord
- https://github.com/Poilerwags/Customa-Discord

The variable (`--BackgroundImg`) in question seems to only be used in their fork, so please open an issue there :)

**Comment by Davoleo** [comment]
ah, you're totally right, sorry for this thread
